name: docker-prysm

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY_IMAGE_PREFIX: ghcr.io/polymerdao/prysm

jobs:
  build:
    runs-on: ubuntu-22.04-16core
    strategy:
      fail-fast: true
      matrix:
        binary:
          - beacon-chain
          - prysmctl
          - validator
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.build-ref }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY_IMAGE_PREFIX }}-${{ matrix.binary }}
          tags: |
            type=sha
            type=semver,pattern={{raw}}
          labels: |
            org.opencontainers.image.source=https://github.com/polymerdao/prysm
            org.opencontainers.image.title=prysm
            org.opencontainers.image.url=https://github.com/polymerdao/prysm

      - name: Authenticate Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Read bazel version
        run: |
          echo "BAZEL_VERSION=$( cat .bazelversion )" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          REGISTRY_IMAGE: ${{ env.REGISTRY_IMAGE_PREFIX }}-${{ matrix.binary }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BINARY=${{ matrix.binary }}
            BAZEL_VERSION=${{ env.BAZEL_VERSION }}
            # TODO: these cause the runner to hang and crash
            # cache-from: type=registry,ref=${{ env.REGISTRY_IMAGE }}:buildcache
            # cache-to: type=registry,ref=${{ env.REGISTRY_IMAGE }}:buildcache,mode=max
